# Generated by Django 5.2.2 on 2025-06-12 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_usersmodels_delete_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersmodels',
            old_name='name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='usersmodels',
            old_name='nickname',
            new_name='username',
        ),
    ]
