# Generated by Django 5.2.2 on 2025-07-28 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labelsmodel',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Имя'),
        ),
    ]
