# Generated by Django 5.2.2 on 2025-07-11 12:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0002_statusesmodel_author'),
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tasksmodel',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='statuses.statusesmodel'),
        ),
        migrations.AlterField(
            model_name='tasksmodel',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_task', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tasksmodel',
            name='executor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='executor_task', to=settings.AUTH_USER_MODEL),
        ),
    ]
