# Generated by Django 5.2.2 on 2025-08-30 19:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('labels', '0002_initial'),
        ('statuses', '0002_initial'),
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tasksmodel',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_task', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tasksmodel',
            name='executor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='executor_task', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель'),
        ),
        migrations.AddField(
            model_name='tasksmodel',
            name='labels',
            field=models.ManyToManyField(related_name='tasks', to='labels.labelsmodel', verbose_name='Метки'),
        ),
        migrations.AddField(
            model_name='tasksmodel',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='statuses.statusesmodel', verbose_name='Статус'),
        ),
    ]
