# Generated by Django 5.2.2 on 2025-07-17 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0001_initial'),
        ('tasks', '0002_tasksmodel_status_alter_tasksmodel_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasksmodel',
            name='labels',
            field=models.ManyToManyField(to='labels.labelsmodel'),
        ),
    ]
