# Generated by Django 5.2.2 on 2025-07-28 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0002_statusesmodel_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusesmodel',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Имя'),
        ),
    ]
